#!/usr/bin/env bash
# Connections sync. PostToolUse (Edit|Write, Bash) + SessionStart.
# connections.md is a pure function of the docs' frontmatter, so it is regenerated by a
# deterministic script the instant a doc changes, never left to a skill to remember. The
# generator writes the file directly (not via a tool), so it cannot retrigger this hook.
# Fails open and silent if node is missing. Never blocks.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/lib/common.sh"

command -v node >/dev/null 2>&1 || exit 0
mdd_read_input
mdd_active || exit 0

event="$(mdd_field '.hook_event_name')"
regen=0
surface=0

case "$event" in
  SessionStart)
    # Catch edits made outside Claude Code, so the map is fresh at the first prompt.
    regen=1 ;;
  *)
    tool="$(mdd_field '.tool_name')"
    case "$tool" in
      Write|Edit|NotebookEdit)
        fp="$(mdd_field '.tool_input.file_path')"
        case "$fp" in
          *"$MDD_DOCS"/archive/*) : ;;            # archived docs are excluded from the map
          *"$MDD_DOCS"/*.md) regen=1; surface=1 ;;
        esac ;;
      Bash)
        # A mv/rm that touches the docs dir changes the graph (e.g. deprecate archiving a doc).
        cmd="$(mdd_field '.tool_input.command')"
        case "$cmd" in
          *"$MDD_DOCS"*) regen=1; surface=1 ;;
        esac ;;
    esac ;;
esac

[ "$regen" -eq 1 ] || exit 0

errfile="$(mktemp)"
warnings="$(MDD_DOCS="$MDD_DOCS" MDD_CONNECTIONS="$MDD_DIR/connections.md" \
  node "$SCRIPT_DIR/lib/connections-gen.cjs" 2>"$errfile")"
rc=$?
if [ $rc -ne 0 ]; then
  err="$(head -c 300 "$errfile" 2>/dev/null | tr '\n' ' ')"; rm -f "$errfile"
  mdd_note "MDD connections generator FAILED to run (exit $rc): ${err:-no stderr}. The connections map is NOT being kept current. Try: bash .claude/hooks/fix-permissions.sh"
fi
rm -f "$errfile"

# Only speak on a doc mutation that introduced a structural problem. Silent otherwise,
# and silent at SessionStart (session-start.sh already carries the orientation line).
if [ "$surface" -eq 1 ] && [ -n "${warnings:-}" ] && [ "${warnings:-0}" != "0" ]; then
  mdd_note "connections.md regenerated with $warnings warning(s): a broken or circular depends_on, or a doc missing 'path'. See .mdd/connections.md."
fi
exit 0
